main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "26.1.2"
author: AUTHOR
description: DESCRIPTION
website: https://oxod.nl

commands:
  plugintemplate:
    description: PluginTemplate plugin
    usage: /<command> <subcommand> [args]
